INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weapongreen', 'Material Green', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponblue2', 'Material Light Blue', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponblue', 'Material Blue', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponblack', 'Material Black', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('partssmg', 'Weapon Parts SMG', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('partsshotgun', 'Weapon Parts Shotgun', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('partsrifle2', 'Weapon Parts Rifle 2', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('partsrifle', 'Weapon Parts Rifle', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponorange', 'Material Orange', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponpurple', 'Material Purple', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponred', 'Material Red', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponyellow', 'Material Yellow', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponwhite', 'Material White', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('partspistol', 'Weapon Parts Pistol', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('mag1', 'MAG1', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magstick4', 'MAG Stick 4', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magstick3', 'MAG Stick 3', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magstick2', 'MAG Stick 2', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magstick', 'MAG Stick', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magdrum8', 'MAG Drum 8', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magdrum7', 'MAG Drum 7', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magdrum6', 'MAG Drum 6', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magdrum5', 'MAG Drum 5', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magdrum4', 'MAG Drum 4', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magdrum3', 'MAG Drum 3', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magdrum2', 'MAG Drum 2', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magdrum', 'MAG Drum', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magclear2', 'MAG Clear 2', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magclear', 'MAG Clear', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('mag2', 'MAG 2', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('magstick5', 'MAG Stick 5', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('diamond', 'Diamond', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('gold_bar', 'Gold Bar', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('platinum_bar', 'Platinum Bar', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('rosegold_bar', 'Rose Gold Bar', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('switch', 'Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('weaponpink', 'Material Pink', 1, 0, 1);



-- Dont install this part if you dont need it

INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_M10', 'M10 GOLD VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MPXVVS', 'MPX VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MPA', 'MPA VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_JAK12', 'JAK12 Iced', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVSYELLOW', 'MP5 Yellow VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVSRED', 'MP5 Red VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVSPURPLE', 'MP5 Purple VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVSGREEN', 'MP5 Green VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVSBLUE2', 'MP5 Light Blue VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSYELLOW', ' DRACO YELLOW VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHBLUE2', 'LIGHT BLUE Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHBLUE', 'BLUE Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHBLACK', 'BLACK Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHDRAGON', 'DRAGON Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHGREEN', 'GREEN Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHORANGE', 'ORANGE Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_YELLOWARP', 'ARP DRUM YELLOW', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_VELVVS', 'VEL46 VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSBLACK', 'G26 DRUM VVS BLACK', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSBLUE', 'G26 DRUM VVS BLUE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSBLUE2', 'G26 DRUM VVS BLUE2', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSGREEN', 'G26 DRUM VVS GREEN', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSORANGE', 'G26 DRUM VVS ORANGE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSPINK', 'G26 DRUM VVS PINK', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSPURPLE', 'G26 DRUM VVS PURPLE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSRED', 'G26 DRUM VVS RED', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26VVSYELLOW', 'G26 DRUM VVS YELLOW', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHYELLOW', 'YELLOW Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHWHITE', 'WHITE Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHRED', 'RED Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SWITCHPURPLE', 'PURPLE Switch', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_REDARP', 'ARP DRUM RED', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSPURPLE', 'DRACO PURPLE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_PURPLEARP', 'ARP DRUM PURPLE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSPLAT', 'DRACO PLATINUM VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_PINKARP', 'ARP DRUM PINK', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSRED', 'DRACO RED VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSPINK', 'DRACO PINK VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SOS', 'PUMP SHOTGUN VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SKELETONARP', 'ARP Skeleton VVS Gold', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SHORTARP2', 'ARP Short', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_SCORPIONVVS', 'SCORPION VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSROSE', 'DRACO ROSE GOLD VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_RKVVS', 'RENETTI KIT VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSORANGE', 'DRACO ORANGE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVSBLUE', 'MP5 Blue VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_9MMARPYELLOW', '9MM ARP YELLOW VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_9MMARPRED', '9MM ARP RED VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_9MMARPPURPLE', '9MM ARP PURPLE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_9MMARPGREEN', '9MM ARP GREEN VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_9MMARPGOLD', '9MM ARP GOLD VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_9MMARPBLUE2', '9MM ARP LIGHT BLUE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_9MMARPBLUE', '9MM ARP BLUE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_9MMARPBLACK', '9MM ARP BLACK VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_AKV9', 'AKV9 VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_300BOVVSYELLOW', '300 BLACKOUT YELLOW', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_300BOVVSRED', '300 BLACKOUT RED', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_300BOVVSPURPLE', '300 BLACKOUT PURPLE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_300BOVVSGREEN', '300 BLACKOUT GREEN', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_300BOVVSBLUE2', '300 BLACKOUT LIGHT BLUE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_300BOVVSBLUE', '300 BLACKOUT BLUE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_300BOVVSBLACK', '300 BLACKOUT BLACK', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_300BOVVS', '300 BLACKOUT WHITE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVSBLACK', 'MP5 BLACK VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVSPINK', 'MP5 PINK VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSGREEN', 'DRACO GREEN VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_GREENARP', 'ARP DRUM GREEN', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSGOLD', 'DRACO GOLD VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_GOLDARP', 'ARP DRUM GOLD', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HAHA74U', '74U VVS GOLD', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVS', 'HK33 GOLD VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVSBLACK', 'HK33 BLACK VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_MP5VVS', 'MP5 Gold VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVSYELLOW', 'HK33 YELLOW VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVSRED', 'HK33 RED VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVSPURPLE', 'HK33 PURPLE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVSORANGE', 'HK33 ORANGE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVSGREEN', 'HK33 GREEN VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVSBLUE2', 'HK33 BLUE2 VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_HK33VVSBLUE', 'HK33 BLUE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_GDRUMVVS', 'GLOCK SWITCH DRUM VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26V2', 'G26 VVS LASER', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSBLACK', 'DRACO BLACK VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_BLACKARP', 'ARP DRUM BLACK', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_AUGVVSYELLOW', 'AUGVVS YELLOW VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_AUGVVSRED', 'AUGVVS RED VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_AUGVVSPURPLE', 'AUGVVS PURPLE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_AUGVVSGREEN', 'AUGVVS GREEN VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_AUGVVSBLUE2', 'AUGVVS LIGHT BLUE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_AUGVVSBLACK', 'AUGVVS BLACK VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_BLUE2ARP', 'ARP LIGHT BLUE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSBLUE2', 'DRACO BLUE2 VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_BLUEARP', 'ARP DRUM BLUE', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G26SWITCH', 'G26 Switch Drum', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G18_APPISTOL', 'G18 Ice', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_G18RED', 'G18 RED VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DEAGLEDRUM', 'DEAGLE DRUM GOLD VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_CX9_SMG', 'CX9 GOLD VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_DRACOVVSBLUE', 'DRACO BLUE VVS', 1, 0, 1);
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('WEAPON_AUGVVS', 'AUGVVS BLUE VVS', 1, 0, 1);
